"""Added contact id field to Group table

Revision ID: ddfdead2aa18
Revises: e321e48e2a84
Create Date: 2023-12-06 00:03:44.614170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfdead2aa18'
down_revision: Union[str, None] = 'e321e48e2a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('contact_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'contact_id')
    # ### end Alembic commands ###
