"""Added contact id to user model (a way to avoid non db id intersection)

Revision ID: e321e48e2a84
Revises: 97feef3036dc
Create Date: 2023-11-28 23:43:08.613101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e321e48e2a84'
down_revision: Union[str, None] = '97feef3036dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact_id', sa.String(), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'contact_id')
    # ### end Alembic commands ###
